import type { Metadata } from "next";
import RootProvider from "@/providers/rootProvider";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar/Navbar";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ScreensLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <RootProvider>
          <div>
            <div className="sticky top-0 z-50">
              <Navbar />
            </div>
            {/* <SearchOverlay /> */}
            <main>{children}</main>
            <Toaster
              toastOptions={{
                classNames: {
                  icon: "text-primary", // icon color
                },
              }}
            />
          </div>
        </RootProvider>
      </body>
    </html>
  );
}
