import type { Metadata } from "next";
import RootProvider from "@/providers/rootProvider";
import { Navbar } from "@/components/navbar/Navbar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ScreensLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootProvider>
      <div>
        <div className="sticky top-0 z-50">
          <Navbar />
        </div>
        {/* <SearchOverlay /> */}
        <main>{children}</main>
        <Toaster
          position="top-center"
          duration={3000}
          closeButton={true}
          toastOptions={{
            classNames: {
              icon: "text-primary", // icon color
              closeButton: "!left-auto !right-2 !top-1/2 !-translate-y-1/2",
            },
          }}
        />
      </div>
    </RootProvider>
  );
}
