import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import RootProvider from "@/providers/rootProvider";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/navbar/Navbar";
import "../../app/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ScreensLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <div className="mx-6 md:mx-8">
          <div className="sticky top-0 z-50">
            <Navbar />
          </div>
          <RootProvider>{children}</RootProvider>
        </div>
      </body>
    </html>
  );
}
