export const discoverMockData = [
  {
    id: 1,
    title: "Masala Dosa",
    description:
      "Crispy dosa filled with flavorful potato masala, served with coconut chutney and sambar — a timeless South Indian favorite.",
    image: "/images/recipe.png",
    category: "Breakfast",
    timeNeeded: "1 hour",
    difficulty: "Hard",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "2 cups cooked white rice",
      "2 tablespoons vegetable oil",
      "1 onion, chopped",
      "2 carrots, diced",
      "1 red bell pepper, diced",
      "1 cup frozen peas",
      "3 cloves garlic, minced",
      "2 tablespoons soy sauce",
      "1 teaspoon sesame oil",
      "2 eggs, beaten",
    ],
    instructions: [
      "Heat a large skillet or wok over medium-high heat. Add 1 tablespoon of vegetable oil.",
      "Once the oil is hot, add the chopped onion and sauté for a couple of minutes.",
      "Add the diced carrots and bell pepper. Stir-fry for about 3-4 minutes.",
      "Push the vegetables to one side. Add remaining oil and pour in beaten eggs.",
      "Scramble the eggs until just set, then mix with the vegetables.",
      "Add the cooked rice, breaking up any clumps. Stir-fry for 2-3 minutes.",
      "Add frozen peas and garlic. Continue to stir-fry for another 2 minutes.",
      "Drizzle soy sauce and sesame oil. Toss until well combined.",
      "Season with salt and pepper to taste. Serve hot.",
    ],
  },
  {
    id: 2,
    title: "Bisi Bele Bath",
    description:
      "Crispy dosa filled with flavorful potato masala, served with coconut chutney and sambar — a timeless South Indian favorite.",
    image: "/images/image1.jpg",
    category: "Lunch",
    timeNeeded: "1 hour",
    difficulty: "Medium",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "2 cups cooked white rice",
      "2 tablespoons vegetable oil",
      "1 onion, chopped",
    ],
    instructions: [
      "Heat a large skillet or wok over medium-high heat. Add 1 tablespoon of vegetable oil.",
      "Once the oil is hot, add the chopped onion and sauté for a couple of minutes.",
      "Add the diced carrots and bell pepper. Stir-fry for about 3-4 minutes.",
    ],
  },
  {
    id: 3,
    title: "Ragi Mudde",
    description:
      "Crispy dosa filled with flavorful potato masala, served with coconut chutney and sambar — a timeless South Indian favorite.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "30 mins",
    difficulty: "Easy",
    servings: 4,
    isFavorite: true,
    ingredients: [
      "2 cups cooked white rice",
      "2 tablespoons vegetable oil",
      "1 onion, chopped",
    ],
    instructions: [
      "Heat a large skillet or wok over medium-high heat. Add 1 tablespoon of vegetable oil.",
      "Once the oil is hot, add the chopped onion and sauté for a couple of minutes.",
      "Add the diced carrots and bell pepper. Stir-fry for about 3-4 minutes.",
    ],
  },
  {
    id: 4,
    title: "Huli",
    description:
      "Crispy dosa filled with flavorful potato masala, served with coconut chutney and sambar — a timeless South Indian favorite.",
    image: "/images/image1.jpg",
    category: "Snack",
    timeNeeded: "20 mins",
    difficulty: "Easy",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "2 cups cooked white rice",
      "2 tablespoons vegetable oil",
      "1 onion, chopped",
    ],
    instructions: [
      "Heat a large skillet or wok over medium-high heat. Add 1 tablespoon of vegetable oil.",
      "Once the oil is hot, add the chopped onion and sauté for a couple of minutes.",
      "Add the diced carrots and bell pepper. Stir-fry for about 3-4 minutes.",
    ],
  },
  {
    id: 5,
    title: "Saaru",
    description:
      "Crispy dosa filled with flavorful potato masala, served with coconut chutney and sambar — a timeless South Indian favorite.",
    image: "/images/image1.jpg",
    category: "Lunch",
    timeNeeded: "45 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: true,
    ingredients: [
      "2 cups cooked white rice",
      "2 tablespoons vegetable oil",
      "1 onion, chopped",
    ],
    instructions: [
      "Heat a large skillet or wok over medium-high heat. Add 1 tablespoon of vegetable oil.",
      "Once the oil is hot, add the chopped onion and sauté for a couple of minutes.",
      "Add the diced carrots and bell pepper. Stir-fry for about 3-4 minutes.",
    ],
  },
  {
    id: 6,
    title: "Tellevu",
    description:
      "Crispy dosa filled with flavorful potato masala, served with coconut chutney and sambar — a timeless South Indian favorite.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "30 mins",
    difficulty: "Easy",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "2 cups cooked white rice",
      "2 tablespoons vegetable oil",
      "1 onion, chopped",
    ],
    instructions: [
      "Heat a large skillet or wok over medium-high heat. Add 1 tablespoon of vegetable oil.",
      "Once the oil is hot, add the chopped onion and sauté for a couple of minutes.",
      "Add the diced carrots and bell pepper. Stir-fry for about 3-4 minutes.",
    ],
  },
  {
    id: 7,
    title: "Idli Sambar",
    description:
      "Soft, fluffy steamed rice cakes served with piping hot lentil sambar and an array of chutneys — a beloved South Indian breakfast staple.",
    image: "/images/image1.jpg",
    category: "Breakfast",
    timeNeeded: "45 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "2 cups idli rice",
      "1 cup urad dal",
      "1 tsp fenugreek seeds",
      "Salt to taste",
      "1 cup toor dal",
      "2 tomatoes, chopped",
      "1 onion, chopped",
      "2 tbsp tamarind paste",
    ],
    instructions: [
      "Soak rice and urad dal separately for 6 hours.",
      "Grind urad dal to a smooth batter, then grind rice coarsely.",
      "Mix both batters, add salt, and ferment overnight.",
      "Pour batter into greased idli molds and steam for 10-12 minutes.",
      "For sambar, cook toor dal until soft.",
      "Sauté onions, tomatoes, and add tamarind paste.",
      "Combine with cooked dal and simmer for 15 minutes.",
      "Serve hot idlis with sambar and chutney.",
    ],
  },
  {
    id: 8,
    title: "Vada Pav",
    description:
      "Mumbai's iconic street food — a spiced potato fritter nestled in a soft bread roll with zesty chutneys.",
    image: "/images/image1.jpg",
    category: "Snack",
    timeNeeded: "40 mins",
    difficulty: "Medium",
    servings: 6,
    isFavorite: true,
    ingredients: [
      "6 pav buns",
      "4 medium potatoes, boiled and mashed",
      "1 cup chickpea flour",
      "1 tsp mustard seeds",
      "2 green chilies, chopped",
      "1/2 tsp turmeric",
      "Fresh coriander leaves",
      "Oil for frying",
    ],
    instructions: [
      "Mix mashed potatoes with mustard seeds, green chilies, turmeric, and coriander.",
      "Shape into round patties.",
      "Make a thick batter with chickpea flour, turmeric, and water.",
      "Dip each patty in batter and deep fry until golden.",
      "Slice pav buns and apply green and tamarind chutney.",
      "Place the vada inside and serve immediately.",
    ],
  },
  {
    id: 9,
    title: "Chicken Biryani",
    description:
      "Fragrant basmati rice layered with spiced chicken, caramelized onions, and saffron — a royal feast in every bite.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "2 hours",
    difficulty: "Hard",
    servings: 6,
    isFavorite: true,
    ingredients: [
      "2 cups basmati rice",
      "500g chicken pieces",
      "2 onions, thinly sliced",
      "1 cup yogurt",
      "2 tbsp biryani masala",
      "1/2 tsp saffron soaked in warm milk",
      "4 tbsp ghee",
      "Fresh mint and coriander leaves",
    ],
    instructions: [
      "Marinate chicken in yogurt and biryani masala for 1 hour.",
      "Fry onions in ghee until deeply caramelized. Set aside.",
      "Parboil rice with whole spices until 70% cooked.",
      "Cook marinated chicken in a heavy pot until half done.",
      "Layer parboiled rice over chicken.",
      "Top with fried onions, saffron milk, and fresh herbs.",
      "Seal pot with dough or foil and cook on low heat for 30 minutes.",
      "Gently mix and serve with raita.",
    ],
  },
  {
    id: 10,
    title: "Pani Puri",
    description:
      "Crispy hollow shells filled with tangy tamarind water, spiced potatoes, and chickpeas — an explosion of flavor in one bite.",
    image: "/images/image1.jpg",
    category: "Snack",
    timeNeeded: "30 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: true,
    ingredients: [
      "20 puri shells (store-bought or homemade)",
      "1 cup boiled chickpeas",
      "2 potatoes, boiled and mashed",
      "1/2 cup tamarind pulp",
      "1 tsp cumin powder",
      "1 tsp chaat masala",
      "Fresh mint leaves",
      "2 green chilies",
    ],
    instructions: [
      "Blend mint, green chilies, cumin, and chaat masala with water for pani.",
      "Strain the mixture and refrigerate.",
      "Mix mashed potatoes with chickpeas and chaat masala.",
      "Make a small hole in each puri shell.",
      "Fill with potato-chickpea mixture.",
      "Dip into chilled pani just before eating.",
    ],
  },
  {
    id: 11,
    title: "Dal Makhani",
    description:
      "Slow-cooked black lentils simmered overnight in butter and cream — a rich, deeply indulgent North Indian classic.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "8 hours",
    difficulty: "Hard",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "1 cup whole black lentils (urad dal)",
      "1/4 cup kidney beans",
      "3 tbsp butter",
      "1 cup tomato puree",
      "1/2 cup heavy cream",
      "1 tsp cumin seeds",
      "1 tbsp ginger-garlic paste",
      "1 tsp garam masala",
    ],
    instructions: [
      "Soak lentils and kidney beans overnight.",
      "Pressure cook until very soft.",
      "Melt butter in a pan, add cumin seeds and ginger-garlic paste.",
      "Add tomato puree and cook until oil separates.",
      "Add cooked lentils and simmer on very low heat for 2 hours.",
      "Stir in cream and garam masala.",
      "Continue simmering for another 30 minutes.",
      "Finish with a dollop of butter before serving.",
    ],
  },
  {
    id: 12,
    title: "Upma",
    description:
      "A savory semolina porridge tempered with mustard seeds, curry leaves, and vegetables — a quick and comforting South Indian breakfast.",
    image: "/images/image1.jpg",
    category: "Breakfast",
    timeNeeded: "20 mins",
    difficulty: "Easy",
    servings: 2,
    isFavorite: false,
    ingredients: [
      "1 cup semolina (rava)",
      "2 tbsp oil",
      "1 tsp mustard seeds",
      "1 tsp urad dal",
      "10 curry leaves",
      "1 onion, chopped",
      "2 green chilies, slit",
      "2 cups water",
    ],
    instructions: [
      "Dry roast semolina until lightly golden. Set aside.",
      "Heat oil and add mustard seeds and urad dal.",
      "Once seeds splutter, add curry leaves, chilies, and onion.",
      "Sauté until onions are translucent.",
      "Add water and salt, bring to a boil.",
      "Slowly add roasted semolina, stirring continuously.",
      "Cook on low heat until all water is absorbed.",
      "Serve warm with coconut chutney.",
    ],
  },
  {
    id: 13,
    title: "Chole Bhature",
    description:
      "Spiced white chickpea curry paired with pillowy deep-fried bread — a hearty and festive North Indian combination.",
    image: "/images/image1.jpg",
    category: "Lunch",
    timeNeeded: "1.5 hours",
    difficulty: "Hard",
    servings: 4,
    isFavorite: true,
    ingredients: [
      "2 cups dried chickpeas, soaked overnight",
      "2 cups all-purpose flour",
      "1/2 cup yogurt",
      "2 onions, finely chopped",
      "2 tomatoes, pureed",
      "2 tbsp chole masala",
      "1 tsp baking powder",
      "Oil for deep frying",
    ],
    instructions: [
      "Pressure cook soaked chickpeas until tender.",
      "Make dough with flour, yogurt, baking powder, and water. Rest for 1 hour.",
      "Sauté onions until golden, add tomato puree and chole masala.",
      "Add chickpeas and simmer for 20 minutes.",
      "Roll dough into circles and deep fry until puffed and golden.",
      "Serve hot chole with bhature and sliced onions.",
    ],
  },
  {
    id: 14,
    title: "Rasam",
    description:
      "A thin, tangy tomato and tamarind broth spiced with black pepper and cumin — a soothing South Indian soup often enjoyed with rice.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "25 mins",
    difficulty: "Easy",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "2 tomatoes, crushed",
      "2 tbsp tamarind paste",
      "1 tsp black pepper, coarsely ground",
      "1 tsp cumin seeds",
      "1/4 cup cooked toor dal",
      "2 dried red chilies",
      "10 curry leaves",
      "1 tbsp ghee",
    ],
    instructions: [
      "Dissolve tamarind in 2 cups of warm water.",
      "Add crushed tomatoes and bring to a boil.",
      "Stir in cooked dal and black pepper.",
      "Simmer for 10 minutes until fragrant.",
      "Prepare tempering with ghee, cumin, red chilies, and curry leaves.",
      "Pour tempering over rasam.",
      "Adjust salt and serve hot with steamed rice.",
    ],
  },
  {
    id: 15,
    title: "Poha",
    description:
      "Flattened rice tossed with turmeric, onions, and peanuts — a light yet satisfying breakfast loved across central India.",
    image: "/images/image1.jpg",
    category: "Breakfast",
    timeNeeded: "15 mins",
    difficulty: "Easy",
    servings: 2,
    isFavorite: false,
    ingredients: [
      "2 cups flattened rice (poha)",
      "1 onion, finely chopped",
      "1/4 cup roasted peanuts",
      "1 tsp mustard seeds",
      "1/2 tsp turmeric",
      "10 curry leaves",
      "2 green chilies, slit",
      "2 tbsp oil",
    ],
    instructions: [
      "Rinse poha gently and drain. Let it soften for 5 minutes.",
      "Heat oil, add mustard seeds, curry leaves, and green chilies.",
      "Add onions and sauté until soft.",
      "Stir in turmeric and peanuts.",
      "Add softened poha and mix gently.",
      "Cook for 2-3 minutes, stirring occasionally.",
      "Garnish with coriander and a squeeze of lemon. Serve warm.",
    ],
  },
  {
    id: 16,
    title: "Fish Curry",
    description:
      "Tender fish simmered in a bold coconut and tamarind gravy with warming spices — a coastal Indian staple full of depth.",
    image: "/images/image1.jpg",
    category: "Lunch",
    timeNeeded: "45 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "500g firm white fish, cut into pieces",
      "1 cup coconut milk",
      "2 tbsp tamarind paste",
      "1 onion, finely chopped",
      "3 tomatoes, chopped",
      "1 tsp turmeric",
      "2 tsp red chili powder",
      "2 tbsp coconut oil",
    ],
    instructions: [
      "Heat coconut oil and sauté onions until golden.",
      "Add tomatoes and cook until mushy.",
      "Stir in turmeric, chili powder, and tamarind paste.",
      "Pour in coconut milk and bring to a simmer.",
      "Add fish pieces and cook for 12-15 minutes.",
      "Adjust seasoning and serve with steamed rice.",
    ],
  },
  {
    id: 17,
    title: "Aloo Paratha",
    description:
      "Whole wheat flatbread stuffed with spiced mashed potatoes, pan-fried in butter — a beloved North Indian breakfast and comfort food.",
    image: "/images/image1.jpg",
    category: "Breakfast",
    timeNeeded: "40 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: true,
    ingredients: [
      "2 cups whole wheat flour",
      "3 medium potatoes, boiled and mashed",
      "1 tsp cumin seeds",
      "2 green chilies, finely chopped",
      "1/2 tsp amchur (dry mango powder)",
      "Fresh coriander, chopped",
      "Butter for cooking",
      "Salt to taste",
    ],
    instructions: [
      "Knead flour with water and salt into a smooth dough. Rest for 20 minutes.",
      "Mix mashed potatoes with cumin, chilies, amchur, and coriander.",
      "Divide dough into balls, roll each into a small circle.",
      "Place potato filling in the center and seal the edges.",
      "Roll out gently into a flat circle.",
      "Cook on a hot griddle with butter until golden spots appear on both sides.",
      "Serve hot with yogurt and pickle.",
    ],
  },
  {
    id: 18,
    title: "Pongal",
    description:
      "A creamy, comforting dish of rice and lentils cooked with black pepper, cumin, and ghee — South India's ultimate soul food.",
    image: "/images/image1.jpg",
    category: "Breakfast",
    timeNeeded: "30 mins",
    difficulty: "Easy",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "1 cup raw rice",
      "1/2 cup split yellow moong dal",
      "2 tbsp ghee",
      "1 tsp black pepper, coarsely crushed",
      "1 tsp cumin seeds",
      "10 cashews",
      "10 curry leaves",
      "Salt to taste",
    ],
    instructions: [
      "Dry roast moong dal until lightly fragrant.",
      "Pressure cook rice and dal together with 4 cups of water and salt.",
      "Mash the cooked mixture to a soft consistency.",
      "Heat ghee in a pan, fry cashews until golden.",
      "Add cumin, black pepper, and curry leaves to the ghee.",
      "Pour tempering over pongal and mix well.",
      "Serve hot with coconut chutney and sambar.",
    ],
  },
  {
    id: 19,
    title: "Palak Paneer",
    description:
      "Cubes of fresh cottage cheese in a vibrant, creamy spinach sauce — a wholesome and iconic North Indian vegetarian dish.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "35 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: true,
    ingredients: [
      "250g paneer, cubed",
      "4 cups fresh spinach leaves",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "1 tbsp ginger-garlic paste",
      "1/2 cup cream",
      "1 tsp cumin seeds",
      "2 tbsp oil",
    ],
    instructions: [
      "Blanch spinach in boiling water for 2 minutes, then blend into a smooth puree.",
      "Heat oil and add cumin seeds.",
      "Sauté onions until golden, add ginger-garlic paste.",
      "Add tomatoes and cook until soft.",
      "Stir in spinach puree and simmer for 5 minutes.",
      "Add paneer cubes and cream.",
      "Cook for another 5 minutes and serve hot with naan or roti.",
    ],
  },
  {
    id: 20,
    title: "Medu Vada",
    description:
      "Crispy golden doughnuts made from seasoned urad dal batter — a classic South Indian snack best paired with sambar and chutney.",
    image: "/images/image1.jpg",
    category: "Snack",
    timeNeeded: "30 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "1 cup urad dal, soaked for 4 hours",
      "1 onion, finely chopped",
      "2 green chilies, finely chopped",
      "10 curry leaves, chopped",
      "1/2 tsp black pepper",
      "1/2 tsp cumin seeds",
      "Salt to taste",
      "Oil for deep frying",
    ],
    instructions: [
      "Drain urad dal and grind to a thick, fluffy batter using minimal water.",
      "Mix in onion, chilies, curry leaves, pepper, and cumin.",
      "Wet your hands, shape batter into rings.",
      "Heat oil to 175°C.",
      "Carefully slide vadas into oil and fry until golden and crisp.",
      "Drain on paper towels and serve immediately with sambar.",
    ],
  },
  {
    id: 21,
    title: "Mutton Rogan Josh",
    description:
      "Slow-braised mutton in a richly aromatic Kashmiri gravy of whole spices, dried chilies, and yogurt — bold and deeply satisfying.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "2 hours",
    difficulty: "Hard",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "750g mutton, bone-in pieces",
      "1 cup yogurt",
      "2 tbsp Kashmiri red chili powder",
      "1 tbsp fennel powder",
      "1 tsp dry ginger powder",
      "4 cardamom pods",
      "4 tbsp mustard oil",
      "Salt to taste",
    ],
    instructions: [
      "Heat mustard oil until smoking, then reduce heat.",
      "Add cardamom pods and fry briefly.",
      "Add mutton and brown well on all sides.",
      "Mix in chili powder, fennel, and ginger powder.",
      "Stir in whisked yogurt and cook until oil separates.",
      "Add 1 cup water, cover, and slow cook for 1.5 hours.",
      "Simmer uncovered to reduce gravy. Serve with rice or naan.",
    ],
  },
  {
    id: 22,
    title: "Lemon Rice",
    description:
      "Tangy rice tempered with mustard seeds, peanuts, and turmeric, finished with a bright squeeze of lemon — a quick South Indian classic.",
    image: "/images/image1.jpg",
    category: "Lunch",
    timeNeeded: "20 mins",
    difficulty: "Easy",
    servings: 2,
    isFavorite: false,
    ingredients: [
      "2 cups cooked rice",
      "Juice of 2 lemons",
      "2 tbsp oil",
      "1 tsp mustard seeds",
      "1/4 cup peanuts",
      "1/2 tsp turmeric",
      "10 curry leaves",
      "2 dried red chilies",
    ],
    instructions: [
      "Heat oil and fry peanuts until golden. Remove and set aside.",
      "In the same oil, add mustard seeds and let them splutter.",
      "Add curry leaves, red chilies, and turmeric.",
      "Add cooked rice and mix gently.",
      "Stir in lemon juice and fried peanuts.",
      "Season with salt and serve at room temperature.",
    ],
  },
  {
    id: 23,
    title: "Gulab Jamun",
    description:
      "Soft milk-solid dumplings soaked in rose-scented sugar syrup — a rich and indulgent Indian dessert for every celebration.",
    image: "/images/image1.jpg",
    category: "Snack",
    timeNeeded: "45 mins",
    difficulty: "Medium",
    servings: 6,
    isFavorite: true,
    ingredients: [
      "1 cup milk powder",
      "1/4 cup all-purpose flour",
      "1/4 tsp baking soda",
      "2 tbsp ghee",
      "3-4 tbsp milk",
      "1.5 cups sugar",
      "1 cup water",
      "1/2 tsp rose water",
    ],
    instructions: [
      "Combine milk powder, flour, baking soda, and ghee.",
      "Add milk gradually to form a soft dough. Rest for 10 minutes.",
      "Make sugar syrup by dissolving sugar in water; add rose water.",
      "Roll dough into small smooth balls with no cracks.",
      "Deep fry on low heat until evenly dark golden.",
      "Drop hot jamuns into warm syrup.",
      "Soak for at least 30 minutes before serving.",
    ],
  },
  {
    id: 24,
    title: "Baingan Bharta",
    description:
      "Flame-roasted eggplant mashed with tomatoes, onions, and spices — a smoky, rustic North Indian dish packed with character.",
    image: "/images/image1.jpg",
    category: "Dinner",
    timeNeeded: "40 mins",
    difficulty: "Easy",
    servings: 3,
    isFavorite: false,
    ingredients: [
      "1 large eggplant",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 green chilies, chopped",
      "1 tbsp ginger-garlic paste",
      "1/2 tsp turmeric",
      "1 tsp cumin seeds",
      "2 tbsp oil",
    ],
    instructions: [
      "Roast eggplant directly over flame until charred all over.",
      "Peel and mash the roasted eggplant flesh.",
      "Heat oil and add cumin seeds.",
      "Sauté onions until golden, add ginger-garlic paste.",
      "Add tomatoes and chilies; cook until soft.",
      "Stir in mashed eggplant and turmeric.",
      "Cook for 10 minutes, stirring occasionally. Serve with roti.",
    ],
  },
  {
    id: 25,
    title: "Kheer",
    description:
      "Slow-cooked creamy rice pudding infused with cardamom, saffron, and nuts — a timeless Indian dessert served at every feast.",
    image: "/images/image1.jpg",
    category: "Snack",
    timeNeeded: "1 hour",
    difficulty: "Easy",
    servings: 6,
    isFavorite: true,
    ingredients: [
      "1 liter full-fat milk",
      "1/4 cup basmati rice",
      "1/2 cup sugar",
      "1/4 tsp cardamom powder",
      "A pinch of saffron",
      "2 tbsp chopped pistachios",
      "2 tbsp chopped almonds",
      "1 tbsp rose water",
    ],
    instructions: [
      "Bring milk to a boil in a heavy-bottomed pot.",
      "Add washed rice and cook on low heat, stirring frequently.",
      "Continue cooking until rice is very soft and milk thickens, about 40 minutes.",
      "Add sugar and saffron; stir well.",
      "Cook for another 10 minutes until desired consistency.",
      "Stir in cardamom, rose water, and half the nuts.",
      "Serve warm or chilled, garnished with remaining nuts.",
    ],
  },
  {
    id: 26,
    title: "Puliyogare",
    description:
      "Tangy tamarind rice seasoned with a complex spice powder and tempered with peanuts and sesame — a bold South Indian temple classic.",
    image: "/images/image1.jpg",
    category: "Lunch",
    timeNeeded: "35 mins",
    difficulty: "Medium",
    servings: 4,
    isFavorite: false,
    ingredients: [
      "2 cups cooked rice",
      "3 tbsp tamarind paste",
      "2 tbsp puliyogare powder",
      "1/4 cup peanuts",
      "1 tbsp sesame seeds",
      "1 tsp mustard seeds",
      "10 curry leaves",
      "3 tbsp sesame oil",
    ],
    instructions: [
      "Heat sesame oil and fry peanuts until crisp. Remove and set aside.",
      "In the same oil, add mustard seeds, curry leaves, and sesame seeds.",
      "Add tamarind paste and cook until thickened.",
      "Stir in puliyogare powder and fry for 2 minutes.",
      "Add cooked rice and mix thoroughly.",
      "Fold in fried peanuts.",
      "Serve at room temperature.",
    ],
  },
];
